 * Serving Flask app 'watson_aristotle_api'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5101
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [08/Sep/2025 06:44:28] "[33mGET /callback?code=m4rfa9ffmuynrrjdg6xh3kfjzrjkcpbs HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 06:44:28] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 06:46:57] "[33mGET /callback?code=n8yqwxmzzq5sd5xfu5mm76xttghy73ka HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 06:47:14] "[33mGET /callback HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 06:58:19] "[33mGET /callback?code=24y6dz4nrqajg22w7hjyrr6yk4qjq7xr HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:29:54] "[33mGET /callback?code=uh29r2qufjpw823rvymgxcbypfegucwj HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:55:14] "GET /health HTTP/1.1" 200 -
127.0.0.1 - - [08/Sep/2025 18:55:21] "[33mGET /test_claude HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:55:40] "[33mGET /hc?week=2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:55:40] "[33mGET /gm?week=2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:55:40] "[33mGET /scout?week=2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:55:40] "[33mGET /all?week=2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:56:01] code 400, message Bad request version ('\x86Â²\x89~\x8dg\x00*zz\x13\x01\x13\x02\x13\x03Ã€,Ã€+ÃŒÂ©Ã€0Ã€/ÃŒÂ¨Ã€')
127.0.0.1 - - [08/Sep/2025 18:56:01] "[31m[1m\x16\x03\x01\x02\x00\x01\x00\x01Ã¼\x03\x03h\x18!YÂ¡Ã—\x1c\x13@G5\x0e\x8eÂ¥\x10Ã«BÃ¹+vÃ§Ãƒ\x0eÂ³Ã‘f\x91eÃšÃ£Ã™\x1b ÂªÃ«\x98SÃŠÂ´>t\x10\x87Ãžc\x1eÃ ViÃ®\x90wh/\x8a\x04\x0d=\x0b\x86Â²\x89~\x8dg\x00*zz\x13\x01\x13\x02\x13\x03Ã€,Ã€+ÃŒÂ©Ã€0Ã€/ÃŒÂ¨Ã€[0m" 400 -
127.0.0.1 - - [08/Sep/2025 18:56:01] code 400, message Bad request version ('yÂºÃ¼c\x10\x86\x8fÃµÂ¦RÂ°Â²\x9aÃ \x80-\x80ÃŸ\x02\x00,ZZ\x13\x01\x13\x02\x13\x03Ã€,Ã€+ÃŒÂ©Ã€0Ã€/ÃŒÂ¨Ã€')
127.0.0.1 - - [08/Sep/2025 18:56:01] "[31m[1m\x16\x03\x01\x02\x00\x01\x00\x01Ã¼\x03\x03[Ã‘Ã–Ã¼ \x17Â°Ã€~QÂ¶\x16Â²\x92ÃŸ\x19\x93vÂ·\x16NÃ¿Â¬^\x08Ã”\x99Ã·o\x154c ÃŽ\x86\x13Ãµtr}Â¿)ÃŽ@\x1b\x85yÂºÃ¼c\x10\x86\x8fÃµÂ¦RÂ°Â²\x9aÃ \x80-\x80ÃŸ\x02\x00,ZZ\x13\x01\x13\x02\x13\x03Ã€,Ã€+ÃŒÂ©Ã€0Ã€/ÃŒÂ¨Ã€[0m" 400 -
127.0.0.1 - - [08/Sep/2025 18:56:01] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00}\x01\x00\x00y\x03\x01u0Â¿\x84gÃ—JÃ™#Â¦')
127.0.0.1 - - [08/Sep/2025 18:56:01] "[31m[1m\x16\x03\x01\x00}\x01\x00\x00y\x03\x01u0Â¿\x84gÃ—JÃ™#Â¦\x1fÃ \x86Ã”q\x14Â®\x94nÂ½{1c\x8f\x88*Ã‘2ÂµÃ¨\x02#\x00\x00\x14Ã€[0m" 400 -
127.0.0.1 - - [08/Sep/2025 18:58:50] "GET /health HTTP/1.1" 200 -
127.0.0.1 - - [08/Sep/2025 18:58:50] "[33mGET /test_claude HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:58:50] "[33mGET /hc?week=2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 18:58:50] "[33mGET /all?week=2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 19:02:45] "GET /health HTTP/1.1" 200 -
127.0.0.1 - - [08/Sep/2025 19:02:45] "[33mGET /test_claude HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 19:02:45] "[33mGET /hc?week=2 HTTP/1.1[0m" 404 -
127.0.0.1 - - [08/Sep/2025 19:02:45] "[33mGET /all?week=2 HTTP/1.1[0m" 404 -
 * Serving Flask app 'watson_aristotle_api'
 * Debug mode: off
Address already in use
Port 5101 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Serving Flask app 'watson_aristotle_api'
 * Debug mode: off
Address already in use
Port 5101 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Serving Flask app 'watson_aristotle_api'
 * Debug mode: off
Address already in use
Port 5101 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Serving Flask app 'watson_aristotle_api'
 * Debug mode: off
Address already in use
Port 5101 is in use by another program. Either identify and stop that program, or start the server with a different port.
 * Serving Flask app 'watson_aristotle_api'
 * Debug mode: off
Address already in use
Port 5101 is in use by another program. Either identify and stop that program, or start the server with a different port.
/usr/local/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/thomasharvey/fantasycpu/watson_aristotle_api.py': [Errno 2] No such file or directory
/usr/local/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/thomasharvey/fantasycpu/watson_aristotle_api.py': [Errno 2] No such file or directory
/usr/local/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/thomasharvey/fantasycpu/watson_aristotle_api.py': [Errno 2] No such file or directory
/usr/local/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/thomasharvey/fantasycpu/watson_aristotle_api.py': [Errno 2] No such file or directory
/usr/local/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/thomasharvey/fantasycpu/watson_aristotle_api.py': [Errno 2] No such file or directory
